#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#define DEFAULT_WIFI_SSID_PRIMARY   "Frohne-Shop-2.4GHz"
#define DEFAULT_WIFI_SSID_SECONDARY "Frohne-2.4GHz"
#define DEFAULT_WIFI_PASSWORD       ""

#define STATIC_FALLBACK_IP          "192.168.1.191"
#define STATIC_FALLBACK_NETMASK     "255.255.255.0"
#define STATIC_FALLBACK_GATEWAY     "192.168.1.1"

#define TCP_CONTROL_PORT            5000

#endif // WIFI_CONFIG_H
