#include <string.h>

#include "tusb.h"

#define ITF_NUM_CDC 0
#define ITF_NUM_CDC_DATA 1
#define ITF_NUM_AUDIO_CONTROL 2
#define ITF_NUM_AUDIO_STREAMING 3
#define ITF_NUM_DFU 4
#define ITF_NUM_TOTAL 5

#define EPNUM_AUDIO_IN 0x81
#define EPNUM_CDC_NOTIF 0x83
#define EPNUM_CDC_OUT 0x04
#define EPNUM_CDC_IN 0x84

#define AUDIO_CS_AC_TOTALLEN \
    (TUD_AUDIO10_DESC_INPUT_TERM_LEN + \
     TUD_AUDIO10_DESC_FEATURE_UNIT_LEN(2) + \
     TUD_AUDIO10_DESC_OUTPUT_TERM_LEN)

#define AUDIO_ONE_ALT_LEN ( \
    TUD_AUDIO10_DESC_STD_AS_LEN + \
    TUD_AUDIO10_DESC_CS_AS_INT_LEN + \
    TUD_AUDIO10_DESC_TYPE_I_FORMAT_LEN(1) + \
    TUD_AUDIO10_DESC_STD_AS_ISO_EP_LEN + \
    TUD_AUDIO10_DESC_CS_AS_ISO_EP_LEN)

#define AUDIO_BLOCK_LEN ( \
    8u + \
    TUD_AUDIO10_DESC_STD_AC_LEN + \
    TUD_AUDIO10_DESC_CS_AC_LEN(1) + \
    TUD_AUDIO10_DESC_INPUT_TERM_LEN + \
    TUD_AUDIO10_DESC_FEATURE_UNIT_LEN(2) + \
    TUD_AUDIO10_DESC_OUTPUT_TERM_LEN + \
    TUD_AUDIO10_DESC_STD_AS_LEN + \
    AUDIO_ONE_ALT_LEN + \
    AUDIO_ONE_ALT_LEN)

#define DDC_CONFIGURATION_LEN ( \
    TUD_CONFIG_DESC_LEN + TUD_CDC_DESC_LEN + AUDIO_BLOCK_LEN + \
    TUD_DFU_DESC_LEN(CFG_TUD_DFU_ALT))

#ifndef CONFIG_TOTAL_LEN
#define CONFIG_TOTAL_LEN DDC_CONFIGURATION_LEN
#endif

#include "ice_usb.h"

_Static_assert(DDC_CONFIGURATION_LEN == CONFIG_TOTAL_LEN,
               "CONFIG_TOTAL_LEN does not match the DDC descriptor");

const uint8_t tud_desc_configuration[CONFIG_TOTAL_LEN] = {
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_TOTAL_LEN, 0x00, 500),
    TUD_CDC_DESCRIPTOR(ITF_NUM_CDC, STRID_CDC, EPNUM_CDC_NOTIF, 8,
                       EPNUM_CDC_OUT, EPNUM_CDC_IN, 64),

    8, TUSB_DESC_INTERFACE_ASSOCIATION,
    ITF_NUM_AUDIO_CONTROL, 2, TUSB_CLASS_AUDIO, 0x00, 0x00, 0x00,
    TUD_AUDIO10_DESC_STD_AC(ITF_NUM_AUDIO_CONTROL, 0x00, 0x00),
    TUD_AUDIO10_DESC_CS_AC(0x0100, AUDIO_CS_AC_TOTALLEN,
                           ITF_NUM_AUDIO_STREAMING),
    TUD_AUDIO10_DESC_INPUT_TERM(0x01, AUDIO_TERM_TYPE_IN_GENERIC_MIC,
                                0x03, 2,
                                AUDIO10_CHANNEL_CONFIG_LEFT_FRONT |
                                AUDIO10_CHANNEL_CONFIG_RIGHT_FRONT,
                                0x00, 0x00),
    TUD_AUDIO10_DESC_FEATURE_UNIT(0x02, 0x01, 0x00,
                                  AUDIO10_FU_CONTROL_BM_MUTE,
                                  0x0000, 0x0000),
    TUD_AUDIO10_DESC_OUTPUT_TERM(0x03, AUDIO_TERM_TYPE_USB_STREAMING,
                                 0x01, 0x02, 0x00),

    TUD_AUDIO10_DESC_STD_AS_INT(ITF_NUM_AUDIO_STREAMING, 0x00, 0x00, 0x00),

    TUD_AUDIO10_DESC_STD_AS_INT(ITF_NUM_AUDIO_STREAMING, 0x01, 0x01, 0x00),
    TUD_AUDIO10_DESC_CS_AS_INT(0x03, 0x01, AUDIO10_DATA_FORMAT_TYPE_I_PCM),
    11, TUSB_DESC_CS_INTERFACE, 0x02, 0x01, 2, 3, 24, 1,
    0x80, 0xbb, 0x00,
    TUD_AUDIO10_DESC_STD_AS_ISO_EP(EPNUM_AUDIO_IN,
        TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ASYNCHRONOUS,
        294, 0x01, 0x00),
    TUD_AUDIO10_DESC_CS_AS_ISO_EP(
        AUDIO10_CS_AS_ISO_DATA_EP_ATT_SAMPLING_FRQ,
        AUDIO10_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_MILLISEC, 0x0001),

    TUD_AUDIO10_DESC_STD_AS_INT(ITF_NUM_AUDIO_STREAMING, 0x02, 0x01, 0x00),
    TUD_AUDIO10_DESC_CS_AS_INT(0x03, 0x01, AUDIO10_DATA_FORMAT_TYPE_I_PCM),
    11, TUSB_DESC_CS_INTERFACE, 0x02, 0x01, 2, 3, 24, 1,
    0x00, 0x77, 0x01,
    TUD_AUDIO10_DESC_STD_AS_ISO_EP(EPNUM_AUDIO_IN,
        TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ASYNCHRONOUS,
        582, 0x01, 0x00),
    TUD_AUDIO10_DESC_CS_AS_ISO_EP(
        AUDIO10_CS_AS_ISO_DATA_EP_ATT_SAMPLING_FRQ,
        AUDIO10_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_MILLISEC, 0x0001),

    TUD_DFU_DESCRIPTOR(ITF_NUM_DFU, CFG_TUD_DFU_ALT, STRID_DFU,
                       DFU_ATTR_CAN_DOWNLOAD, 1000, CFG_TUD_DFU_XFER_BUFSIZE),
};

char const *tud_string_desc[STRID_NUM_TOTAL] = {
    [STRID_LANGID] = USB_LANG_EN,
    [STRID_MANUFACTURER] = USB_MANUFACTURER,
    [STRID_PRODUCT] = USB_PRODUCT,
    [STRID_SERIAL_NUMBER] = usb_serial_number,
    [STRID_VENDOR] = "WWU DDC SDR",
    [STRID_CDC] = "SDR Control",
    [STRID_DFU] = "iCE40 DFU (CRAM)",
};
