// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// -------- //
// ice_cram //
// -------- //

#define ice_cram_wrap_target 0
#define ice_cram_wrap 2
#define ice_cram_pio_version 0

static __pio_const uint16_t ice_cram_program_instructions[] = {
            //     .wrap_target
    0xb842, //  0: nop                    side 1
    0x6021, //  1: out    x, 1
    0xb101, //  2: mov    pins, x         side 0 [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program ice_cram_program = {
    .instructions = ice_cram_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = ice_cram_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ice_cram_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ice_cram_wrap_target, offset + ice_cram_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

