// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------ //
// i2s_rx //
// ------ //

#define i2s_rx_wrap_target 0
#define i2s_rx_wrap 12
#define i2s_rx_pio_version 0

static __pio_const uint16_t i2s_rx_program_instructions[] = {
            //     .wrap_target
    0x20a2, //  0: wait   1 pin, 2
    0x2022, //  1: wait   0 pin, 2
    0xe03f, //  2: set    x, 31
    0x2021, //  3: wait   0 pin, 1
    0x20a1, //  4: wait   1 pin, 1
    0x4001, //  5: in     pins, 1
    0x0043, //  6: jmp    x--, 3
    0x20a2, //  7: wait   1 pin, 2
    0xe03f, //  8: set    x, 31
    0x2021, //  9: wait   0 pin, 1
    0x20a1, // 10: wait   1 pin, 1
    0x4001, // 11: in     pins, 1
    0x0049, // 12: jmp    x--, 9
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program i2s_rx_program = {
    .instructions = i2s_rx_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = i2s_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config i2s_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_rx_wrap_target, offset + i2s_rx_wrap);
    return c;
}
#endif

